Libs: switch to stable versions
error: packages/modules/DnsResolver/Android.bp:87:1: module "libnetd_resolv" variant "android_arm64_armv8-a_static":
	dnsresolver_aidl_interface-unstable-ndk_platform is disallowed in release version because it is unstable.
error: packages/modules/DnsResolver/Android.bp:87:1: module "libnetd_resolv" variant "android_arm64_armv8-a_static":
	netd_event_listener_interface-unstable-ndk_platform is disallowed in release version because it is unstable.

Change-Id: Ib85203a62c9bb4a6332c96160407ad8c92641d46